blank_issues_enabled: false
contact_links:
  - name: 💬 Slack
    url: https://patriciamcphee.slack.com/archives/D03K6BRHTHN
    about: Chat with other users and the development team
  - name: 📄 Documentation
    url: https://patriciamcphee.github.io/portfolio
    about: Review writing samples
