name: ✨ Feature Request
description: Suggest an idea
labels: ['🌟 enhancement']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
        Use this section to give a description of what your suggestion is about.

        - Title:
        - Who is this for:

        Please select or describe the audience your proposal targets in terms of
        readers' familiarity with Beyond Identity:

        - [ ] Beyond Identity Secure Workforce users
        - [ ] Those interested in passwordless authentication
        - [ ] Those not aware of passwordless authentication yet
        - [ ] Others:

        - Outline:

        - Are there any particular tools, concepts, languages or platforms that readers
          will learn about?
  - type: textarea
    id: suggestion-title
    attributes:
      label: Title
      description: Please provide a descriptive title for your suggestion.
    validations:
      required: true
  - type: textarea
    id: suggestion-audience
    attributes:
      label: Audience 
      description: Please provide a descriptive title for your suggestion.
      value: |
        Please select or describe the audience your proposal targets in terms of readers' familiarity with Beyond Identity:

          - [ ] Beyond Identity Secure Workforce users
          - [ ] Those interested in passwordless authentication
          - [ ] Those not aware of passwordless authentication yet
          - [ ] Others:
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Please provide a clear and concise description of the rationale behind this request.
    validations:
      required: true
  - type: textarea
    id: desired-behavior
    attributes:
      label: Desired Behavior
      description: Provide a clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Provide any additional information or screenshots that may be relevant or helpful.
  - type: markdown
    attributes:
      value: |
        By submitting this feature request, I agree to follow the [code of conduct](https://resoto.com/code-of-conduct).
